import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/">HomePage</Link>
        </li>
        <li>
          <Link to="/mainpage">MainPage</Link>
        </li>
        <li>
          <Link to="/hackathons">Hackathons</Link>
        </li>
        <li>
          <Link to="/profile">Profile</Link>
        </li>
        <li>
          <Link to="/marketplace">Marketplace</Link>
        </li>
        <li>
          <Link to="/hackathonpage">HackathonPage</Link>
        </li>
        <li>
          <Link to="/hackathondetails">HackathonDetails</Link>
        </li>
        <li>
          <Link to="/projectpageprojectinfo">ProjectPageProjectInfo</Link>
        </li>
        <li>
          <Link to="/projectpageteam">ProjectPageTeam</Link>
        </li>
        <li>
          <Link to="/projectpageprojectlinks">ProjectPageProjectLinks</Link>
        </li>
        <li>
          <Link to="/projectpagecalendar">ProjectPageCalendar</Link>
        </li>
        <li>
          <Link to="/projectpagepresentation">ProjectPagePresentation</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
